### ISSUE TITLE
Download link for wildfly_exporter_module is broken

### ISSUE THREAD

**Issue by palashbhowmick** [nlighten/wildfly_exporter#6]
In README.md there is a download link for latest wildfly exporter module. That link is not working.
https://github.com/nlighten/wildfly_exporter#add-exporter-module-jars-to-wildfly

**Comment by felzan** [comment]
Try this one: https://search.maven.org/search?q=a:wildfly_exporter_module

**Comment by palashbhowmick** [comment]
Yes, the link is working but the README file should be updated with the link you provided.
